### ISSUE TITLE
Please consider security alerts

### ISSUE THREAD

**Issue by axel3rd** [GroupePSA/psa-business-theme#1]
A [security alert is open on lodash ](https://github.com/GroupePSA/psa-business-theme/network/alert/yarn.lock/lodash/open) since July 14. It should be reviewed.
Perhaps a *Dismiss* can be done, but receiving weekly email about it is shitting.
Many thanks.

**Comment by axel3rd** [comment]
Some new security alerts today, so global [alerts review](https://github.com/GroupePSA/psa-business-theme/network/alerts) should be done.

**Comment by adrienlauer** [comment]
Done in 713721dd4d8f81123ba13874d1e68f16f2b4b6d5. Thanks for reporting!
